[feat] 업적 페이지 조회, 업적 변경 API 연결
Open-Eye-Im-Developer/MoGakGo-FE pull request #102
Opened 2024-03-05 02:54 UTC by mibu119

# 📌 작업 내용
- [x] 업적 페이지 관련 컴포넌트들의 스타일을 변경하였습니다.
- [x] 남은 달성 횟수가 3 미만인 경우 다음과 같이 표시됩니다.
<img src="https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/114740795/b6009b3e-2c7c-46c3-9590-ba1fb6187c9f" width="200" />

- [x] 남은 달성 횟수가 3회 이상인 경우 다음과 같이 표시됩니다.
<img src="https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/114740795/c2cff49f-1efb-44fc-9b98-0f0dda30266b" width="200" />

# 🚦 특이 사항
- 주의깊게 봐야하는 PR 포인트 & 말하고 싶은 점을 작성해주세요.

close #87

2024-03-05 10:35 UTC, coggiee approved these changes
수고하셨습니다.👍

2024-03-05 10:35 UTC, coggiee commented on app/achievements/_components/AchievementDrawer.tsx
> +            </>
text 색상 스타일 제외하고 중복되는 부분인 것 같아서, `cn`을 사용해서 스타일만 변경하는 건 어떨까요?

2024-03-05 10:35 UTC, coggiee commented on app/achievements/_components/AchievementProgress.tsx
>        )}
분기 처리가 따로 없는 것 같은데 `cn`을 사용하신 이유가 있으신가요?

2024-03-05 11:23 UTC, paul01010 commented on app/achievements/_components/AchievementDrawer.tsx
> +              {total - nowGrade <= 3 ? (
`{total - nowGrade <= 3` 가 무슨 의미인지 변수에 담아서 표현해주면 좋을것같아요

2024-03-07 03:29 UTC, mibu119 commented on app/achievements/_components/AchievementProgress.tsx
>        )}
`cn`은 shadcn이 제공해준 util 함수로, 내부 로직을 보시면 `twMerge` 라는 것이 있어요.
이 [`twMerge`](https://xionwcfm.tistory.com/322) 라는 기능을 사용하려고 했습니다!

사실 이건.. 비밀이지만 해당 progress는 shadcn이 생성해서 생긴 `shadcn > ui` 폴더에 있는 `progress.tsx`를 커스텀하기만 한 파일이라서 아마 똑같이 사용하고 있는걸 그대로 가져와서 `cn`이 남아있던 것입니다..하하

근데 아무래도 `cn`이 분기 처리만을 위해서 사용하는 것은 아니라 남겨둬도 된다고 생각하고 있습니다!

2024-03-07 03:30 UTC, mibu119 commented on app/achievements/_components/AchievementDrawer.tsx
> +            </>
저도 그게 고민이 되는데 되게 작은 부분이지만 어떻게해야 재사용 컴포넌트 잘 만들었다...할지 고민이라서 더 고민해보고 리팩토링에 반영하겠습니다!

2024-03-09 06:33 UTC, bel1c10ud requested changes
리뷰가 너무 늦었네요. 고생 많으셨습니다. 🙂
빌드 에러 관련해서 코멘트 남겨 놓았습니다.

2024-03-09 06:33 UTC, bel1c10ud commented on app/signup/_type/signup.ts
`app/_common/components/NavigationProfile.tsx` 와 
`app/signup/_hooks/useMutationSignup.ts` 에서 에러가 발생해서 빌드가 안되고 있는데요.

아마도 `SignUpUser`에 있던 `achievementTitle`의 위치가 `User` 타입을 확장하고 있는 `UserAchievement`로 변경되면서 그런 것 같아요.

아래처럼 `SignUpUser` 타입을 `User`로 수정해주시면 정상적으로 빌드 될 것 같습니다.

```js
// app/_common/components/NavigationProfile.tsx

// 기존
interface NavigationProfileProps {
  user: Partial<SignUpUser>;
}

// 변경
interface NavigationProfileProps {
  user: Partial<User>;
}
```

```js
// app/_common/components/NavigationProfile.tsx

// 기존
const { mutate } = useMutation({
  mutationFn: patchSignup,
  onSuccess: (data: SignUpUser) => {
  // ... 
  }
})
  
// 변경
const { mutate } = useMutation({
  mutationFn: patchSignup,
  onSuccess: (data: User) => {
  // ... 
  }
})
```

2024-03-09 06:33 UTC, bel1c10ud commented on app/achievements/_components/AchievementList.tsx
> +  const { data: achievements } = useQueryAchievements(user!.id);
user가 null이 아님을 단언해주려면 user가 null인 경우에 대한 최소한의 예외 처리가 필요할 것 같아요.

저는 보통 user가 null이 아님을 단언하기보다 useQuery의 enabled 옵션을 이용해서 user가 null인 경우 fetch하지 않도록 하고 있어요.

2024-03-09 07:16 UTC, mibu119 commented on app/signup/_type/signup.ts
`useMutationSignup.ts` `NavigationProfile.tsx`의 기존 상태로 변경하고 `SignupUser type`을 수정하였으니 다시 확인부탁드립니다.

2024-03-10 06:39 UTC, coggiee commented on app/achievements/_components/AchievementProgress.tsx
>        )}
오호,,, `cn`이 분기처리만 수행하는게 아니군요..??

2024-03-10 06:40 UTC, coggiee approved these changes

2024-03-11 01:28 UTC, bel1c10ud approved these changes

2024-03-11 01:45 UTC, bgyoons reviewed
고생 많으셨습니다 👍

2024-03-11 01:45 UTC, bgyoons commented on app/_common/types/user.ts
> +export interface UserAchievement {
👍

2024-03-11 01:45 UTC, bgyoons commented on app/achievements/_components/AchievementList.tsx
> +  const myAchievement = achievements?.find(
`myAchievement`가 `useQueryAchievements`에서 내려주는 반환값에 영향을 받고 있으니까 해당 훅에서 `myAchievement`도 계산한 다음에 내려주는건 어떨까요?
그러면 해당 컴포넌트에서 아래처럼 사용할 수 있을 것 같아서요!
저는 보통 훅에서 로직 처리하고 데이터민 내려보내주는걸 좋아해서 한번 추천드려봅니다 :D

```ts
const { achievements, myAchievement } = useQueryAchievements(user?.id as number);
```
```ts
// useQueryAchievements.ts

export const useQueryAchievements = (userId: Achievement["userId"]) => {
  const { data, isLoading } = useQuery<Achievement[]>({
    queryKey: ["achievements", userId],
    queryFn: () => getAchievements(userId),
    enabled: !!userId,
  });

  if (!data || isLoading) return { achievements: [], myAchievement: "" }

  return { 
    achievements: data, 
    myAchievement: data.find(
      achievement => achievement.achievementId === userData?.achievementId
    )
  }
};
```

2024-03-11 01:45 UTC, bgyoons commented on app/achievements/_components/AchievementList.tsx
> +            <p>획득한 업적으로 &apos;대표 뱃지&apos;을 변경할 수 있어요.</p>
`뱃지을` > `뱃지를`로 변경해주셔야 할 것 같아요!

2024-03-11 01:45 UTC, bgyoons commented on app/achievements/_components/AchievementItem.tsx
> +  styleType: "main" | "item";
"main"이랑 "item"의 차이는 무엇인가요?

2024-03-11 01:45 UTC, bgyoons commented on app/achievements/_components/AchievementItem.tsx
> +          {title ?? ""}
[`??` 연산자](https://ko.javascript.info/nullish-coalescing-operator)는 `nullish`(`undefined`이거나 `null`) 값만 판단하는 거로 알고 있어요!
`title`의 타입을 보니 `string`인데 `string | null`로 오고 있는걸까요?
 그게 아니라면 falsy 값을 판단하는 `||` 연산자로 바꾸거나 비어있는 경우에 빈 문자열만 온다면 `title`만 둬도 괜찮을 것 같아보여요

2024-03-11 01:45 UTC, bgyoons commented on app/achievements/_utils/calculateAchievement.ts
해당 유틸 테스트 빠진 것 같아요! 
작업 많으시면 추후에 이슈 따로 생성해서 작업해도 상관없을 것 같고요 ㅎㅎ

2024-03-11 01:45 UTC, bgyoons commented on app/achievements/page.tsx
> +export const dynamic = "force-dynamic";
오! 이 부분에서 다이나믹 렌더링이 필요한 이유가 궁금합니다!

2024-03-11 02:16 UTC, mibu119 commented on app/achievements/_components/AchievementList.tsx
> +  const myAchievement = achievements?.find(
오 너무 좋은 아이디어 감사합니다!

2024-03-11 02:18 UTC, mibu119 commented on app/achievements/_components/AchievementItem.tsx
> +  styleType: "main" | "item";
main은 대표 업적 뱃지 스타일이고, item은 리스트의 Item 스타일이라서 이렇게 작성했어요!

2024-03-11 02:18 UTC, mibu119 commented on app/achievements/_utils/calculateAchievement.ts
헉 몰랐어요 감사합니다.

2024-03-11 02:19 UTC, mibu119 commented on app/achievements/page.tsx
> +export const dynamic = "force-dynamic";
그 이유는 포스트에 작성해두어서 글의 특이사항 참고해주세요!

2024-03-11 02:21 UTC, mibu119 commented on app/achievements/_components/AchievementList.tsx
> +  const myAchievement = achievements?.find(
아 좋은 아이디어인데 이렇게 하려면 parameter로 userData 자체를 가져오도록 수정해야되겠네요

2024-03-11 02:46 UTC, mibu119 commented on app/achievements/_utils/calculateAchievement.ts
오잉 확인해보니까 test 폴더에 해당 유틸 함수 test가 있어요!

2024-03-11 03:20 UTC, bgyoons commented on app/achievements/_utils/calculateAchievement.ts
오..! 그랬군요 PR만 확인을 하다보니 이런 실수 리뷰를 ,,머쓱 ,,

2024-03-11 03:22 UTC, bgyoons approved these changes
LGTM 👍

2024-03-11 04:33 UTC, merged