[feat] athorization 기준의 redirects 설정 구현
Open-Eye-Im-Developer/MoGakGo-FE pull request #138
Opened 2024-03-10 13:33 UTC by yougyung

# 📌 작업 내용
- 구현 내용 및 작업 했던 내역, 사진필요한 경우 선택적으로 첨부해주세요.
- [x] athorization을 기준으로 redirect 설정 구현

# 🚦 특이 사항
- 주의깊게 봐야하는 PR 포인트 & 말하고 싶은 점을 작성해주세요.
- `middleware`의 경우 localstorage로 data를 가져오는 것이 불가능 하므로 cookie생성하여 작업을 진행하였습니다
- 채팅 및 알람 페이지의 경우 로그인 한 사용자만 접근하도록 설정했는데, 추가로 설정 희망하시면 `middleware.ts`에 추가해주시면 됩니다 :)
```ts
export const config = {
  matcher: ["/chat/:path*", "/notification"],
};
```
- cookie작업을 위해서는 authorization과 동일한 상태를 가져가야하므로
    - 로그인이 성공한 경우를 시작 지점으로 설정했습니다.
    - 별도로 우리서비스에 로그아웃 기능이 현재 없는 것 같아 탈퇴하거나 404에러가 발생하기 전까지를 기점으로 설정했습니다.
- next 공식문서의 next/headers의 cookies로 작업하고 싶었으나 이는 server 환경에서만 가능하여 아래 에러가 발생했습니다. [비슷한 상황을 공유한 글](https://stackoverflow.com/questions/76595420/how-to-use-cookies-in-client-components-in-next-js-13-and-read-them-on-initial-s)을 찾았지만, next/headers의 cookie를 사용하는 경우 따라오는 특징적 요인이라는 생각이 들어 [cookies-next](https://www.npmjs.com/package/cookies-next)로 쿠키 작업을 진행했습니다. 더 좋은 방법 제안해주시면 리팩토링 진행해보겠습니다 :)
```
 You're importing a component that needs next/headers. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component.
```

2024-03-11 02:50 UTC, coggiee approved these changes
말씀해주신대로 `next/headers`가 제공하는 `cookies`가 클라이언트 환경에서는 동작하지 않아서 고민을 한 번 해봤는데, 로직을 크게 2가지로 분리해봤습니다. 
(유저 삭제와, 회원가입은 제가 지금 수행하면 후처리가 복잡해질 것 같아서 따로 로직 테스트는 하지 않았어서 참고만 해주시면 감사하겠습니댜😙)

1. cookie 관리 로직을 server action으로 만들기
2. 해당 cookie 관리 로직을 핸들러로 만들기
---
1. cookie 관리 로직을 server action으로 만들기
```ts
// app/_common/utils/action.ts

"use server";

import { cookies } from "next/headers";

const cookieStore = cookies();

export const setCookie = () => {
  cookieStore.set("isAuthenticated", "true");
};

export const deleteCookie = () => {
  cookieStore.delete("isAuthenticated");
};
```

2. 해당 cookie 관리 로직을 핸들러로 만들기
```ts
// app/_common/utils/cookieHandler.ts
import { deleteCookie, setCookie } from "./action";

export const setHandler = () => {
  setCookie();
};

export const deleteHandler = () => {
  deleteCookie();
};
```
`action.ts`의 함수들을 직접 할당해서 사용하는게 아닌 굳이 `cookieHandler`를 만들어야하는 의문이 들 수도 있는데 아래 오류 때문에 필요합니다.

`Only plain objects, and a few built-ins, can be passed to Server Actions. Classes or null prototypes are not supported.`

정확히는 왜 발생하는지는 모르겠으나, **server action**을 `client component`에서 바로 사용하려고 해서 발생하는 것으로 추측만 하고 있습니다.

그래서 테스트는 해보지 않았지만,`cookieHandler`에 선언된 함수들로 `cookies-next`의 `deleteCookie, setCookie`를 대체하면 되지 않을까라고 생각합니다.

2024-03-11 04:32 UTC, mibu119 requested changes
코멘트 확인해주시고 재확인, 수정 부탁드립니다!

2024-03-11 04:32 UTC, mibu119 commented on app/_common/api/instance.ts
> +      }
해당 부분이 현재 dev merge 되면서 변경되었습니다! 

현재 dev에서는 401 에러가 뜨면 reissue가 동작하고, 404인 경우는 reissue의 error에서 잡혀서 `navigate('/login')`으로 강제 이동하는 로직으로 404 상황을 막을 수 있는 것으로 예상하고 있습니다.

하지만 혹시 모르니 다시 한 번 현재 dev의 instance.ts 코드를 확인하시고, 해당 조건문이 필요하다면 추가해주세요!
instacne.ts의 자세한 코드 변경은 #132 여기서 확인 부탁드립니다.

2024-03-11 04:32 UTC, mibu119 commented on app/signup/_hooks/useMutationSignup.ts
> +      setCookie("isAuthenticated", "true");
해당 상태를 cookie로 저장하신 이유가 있으신가요?

그리고 이미 회원가입한 사용자가 재로그인 할 시에는 해당 Mutation이 동작하는 것이 않기 때문에 `instance.ts`에서 제거된 `"isAuthenticated" `상태가 다시 true로 갱신되지 않을 것 같아요.

2024-03-12 05:45 UTC, bel1c10ud requested changes
고생 많으셨습니다. 🙂

> - cookie작업을 위해서는 authorization과 동일한 상태를 가져가야하므로
>    - 로그인이 성공한 경우를 시작 지점으로 설정했습니다.
>    - 별도로 우리서비스에 로그아웃 기능이 현재 없는 것 같아 탈퇴하거나 404에러가 발생하기 전까지를 기점으로 설정했습니다.

`useSearchTokens.ts`에도 `setCookie`가 추가로 필요할 것 같아요. 코멘트 남겨 놓았습니다.

> next 공식문서의 next/headers의 cookies로 작업하고 싶었으나 이는 server 환경에서만 가능하여 아래 에러가 발생했습니다. [비슷한 상황을 공유한 글](https://stackoverflow.com/questions/76595420/how-to-use-cookies-in-client-components-in-next-js-13-and-read-them-on-initial-s)을 찾았지만, next/headers의 cookie를 사용하는 경우 따라오는 특징적 요인이라는 생각이 들어 [cookies-next](https://www.npmjs.com/package/cookies-next)로 쿠키 작업을 진행했습니다. 더 좋은 방법 제안해주시면 리팩토링 진행해보겠습니다 :)

말씀하신대로 `next/headers`의 특성인 것 같습니다. `next/headers`의 `cookie`에서 클라이언트에서 다룰 수 없는 `httpOnly` 옵션을 다루고 있어서 그런 것 같아요. 
아마 `cookie-next`는 클라이언트 컴포넌트에서 `httpOnly` 같은 옵션은 다룰 수 없을거에요.

```ts
// 쿠키를 생성해주는 route handler
import type { NextApiRequest, NextApiResponse } from 'next'

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  res.status(200).json(req.cookies);
}
```

위 코드는 제가 이전에 개인 프로젝트에서 `httpOnly` 쿠키를 클라이언트에서 생성해야 해서 만들었던 `route handler` 함수인데요. API 요청으로 들어온 쿠키를 `set-cookie`로 `header`에 담아 응답해주는 식으로 동작해요. 아마 휘식님이 언급해주신 `server action`도 내부적으로 비슷한 방식으로 동작하지 않을까 싶습니다.

그런데 조금 더 궁극적으로 생각해보면 `server action`을 통해 쿠키를 생성할 것이라면 `isAuthenticated`을 쿠키로 저장해서 로그인 여부를 판별하기보다 `refreshToken`을 쿠키로 저장하고  `refreshToken`를 기준으로 로그인 여부를 판별하는 방식을 사용하면 `refreshToken`의 만료일도 관리 할 수 있고, XSF 공격으로 탈취할 수도 없게 되니 더 좋지 않을까라는 생각이 들었어요. 🤔

2024-03-15 06:04 UTC, mibu119 approved these changes
정말 많이 공부해서 만드신 것 같다는게 느껴지네요. 💯 
제가 맡았던 부분인데 대신 고생하신 것 같아 죄송하고 감사드려요. 

혹시 이거 만드시면서 참고하신 레퍼런스 있으시다면 공유해주실 수 있으실까요? 정리하면서 더 공부하고 싶어서요.

2024-03-15 06:04 UTC, mibu119 commented on middleware.ts
> +};
merge 후 인증 필요한 도메인 추가는 이곳에 하는거죠? 확인했습니다. 👍

2024-03-18 00:43 UTC, yougyung commented on middleware.ts
> +};
넵 정확합니다 ~ !

2024-03-18 01:13 UTC, yougyung commented
> 정말 많이 공부해서 만드신 것 같다는게 느껴지네요. 💯 제가 맡았던 부분인데 대신 고생하신 것 같아 죄송하고 감사드려요.
> 
> 혹시 이거 만드시면서 참고하신 레퍼런스 있으시다면 공유해주실 수 있으실까요? 정리하면서 더 공부하고 싶어서요.

공부할 수 있는 시간이 되어 좋았습니다 ㅎㅎ
별도로 참고한 레퍼런스는 없고, 주신 리뷰를 반영해서 적용한 부분입니다! 공유를 위해 과정을 정리했으니 아래 포스트 확인해주시면 감사하겠습니다 ~~ !
https://pastoral-topaz-a50.notion.site/middleware-authorization-redirect-5d4dad469e2543e396d011cc5b522109?pvs=4

2024-03-18 02:22 UTC, bel1c10ud approved these changes
고생 많으셨습니다. 🙂

`reIssueAccessToken` 내부 `localStorage.remove('refreshToken')`와 `await` 키워드 부분만 수정하시면 머지 하셔도 될 것 같습니다.

2024-03-18 02:22 UTC, bel1c10ud commented on app/_common/api/instance.ts
> +    const refreshToken = getCookie("refreshToken", "");
`await` 키워드를 안붙여주면 값이 없는 상태에서 요청이 들어가는 것 같아요. 

```suggestion
    const refreshToken = await getCookie("refreshToken", "");
```

![image](https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/86952779/86f9d522-103f-480a-a2e6-b33ea138cb3b)

2024-03-18 02:22 UTC, bel1c10ud commented on app/_common/api/instance.ts
> +    const refreshToken = getCookie("refreshToken", "");
`refreshToken`이 없는 경우에도 항상 문자열로 만들어서 요청을 보내도 동작에는 아무 이상이 없지만 여유가 되신다면 추후 `reIssueAccessToken`을 호출하기 전이나 `reIssueAccessToken` 내부에 API 요청 전에 먼저 로그인 화면으로 이동시키는 로직이 들어가도 괜찮을 것 같아요.

2024-03-18 02:51 UTC, merged