Feat: 회원가입 페이지 구현 (서버 연결 작업중)
Open-Eye-Im-Developer/MoGakGo-FE pull request #18
Opened 2024-02-18 02:12 UTC by mibu119

# 📌 작업 내용
close #1 
![회원가입 예비1](https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/114740795/ee09f5fb-0c4a-48f9-b38c-e8784b41c37c)

- [ ] 회원가입 페이지 VIEW 작업
- [ ] 주언어 순서, 중요도 정렬 util 함수의 테스트 코드 작성
- [ ] 공통으로 사용할 axios instance 생성 (서버 url x)
   - [ ] axios interceptor로 accesstoken 자동 갱신 구현
- [ ] 공통으로 사용될 cookie 파일 생성
     - [ ] cookie의 get, set, has 함수 작업
- [ ] 회원가입, 로그인 서버와 연결
- [ ] query, mutation hook test 코드 작성

# 🚦 특이 사항
- zustand를 공부하면서 작성해보았는데 혹시 잘못된 부분이 있거나 개선 가능한 부분이 있으면 피드백 부탁드립니다.
- axios instance도 생성했는데 혹시 추가로 option을 넣어야하는 게 있다면 알려주세요. 또는 리팩토링 가능한 부분 있다면 알려주세요!

2024-02-18 02:17 UTC, mibu119 commented on app/login/page.tsx
> +  //  }, [])
`StartWithGithubButton` 누르고 비회원이면, singupPage에 들어가면 바로 useQueryGithubLoginUrl을 실행시키고 싶은데
useEffect를 사용하면 렌더링이 두번 되는 문제가 있을까봐 고민됨.

다른 방법이 있다면 레퍼런스 공유해주시면 감사하겠습니다 ㅠ

2024-02-18 05:24 UTC, bel1c10ud requested changes
고생 많으셨습니다. 🙂
3단계에서 진입하자마자 validation 에러 발생하는 문제에 대한 해결 방법을 적어두었습니다.

2024-02-18 05:24 UTC, bel1c10ud commented on app/signup/_components/SignupSecondStep.tsx
> +        <Button size={"lg"} className="w-full" onClick={handleNextStep}>
`type='button'`이 누락되어서 3단계가 아닌 2단계에서 form이 submit되는 문제가 있어요. 🤔
`wanted_job`을 빈 배열로 설정했을 때 3단계 진입하자마자 validation 에러가 발생하는 것도 같은 이유입니다.

2024-02-18 05:24 UTC, bel1c10ud commented on app/signup/_components/SignupForm.tsx
> +      wanted_job: ["BACKEND"],
빈 배열일 때 3단계 진입하자마자 validation 에러가 발생해서 `BACKEND`를 추가하신거면, 아래 `SignupSecondStep.tsx`에 적어둔 부분 수정하시면 해결될 것 같습니다. 🙂

2024-02-18 10:58 UTC, mibu119 commented on app/signup/_components/SignupSecondStep.tsx
> +        <Button size={"lg"} className="w-full" onClick={handleNextStep}>
와 저 이거 때문에 고생했는데 이거 때문이었군요 감사합니다!!!

2024-02-20 01:56 UTC, bel1c10ud submitted a review, later dismissed

2024-02-20 03:09 UTC, bgyoons reviewed
범님!! 
axios 인스턴스도 만들어주시고 쿠키 설정에 등등 신경 쓸게 많으셔서 고생하셨겠어요!
쿠키와 인스턴스 쪽은 조금 더 공부하고 추가로 리뷰하도록 하겠습니다 :D

2024-02-23 13:22 UTC, coggiee commented on app/signup/_components/SignupForm.tsx
> +            handleNextStep={handleNextStep}
wiki에 props로 함수가 전달될 때는 on 접두사를 붙이는 걸로 알고 있습니다!
그래서 `onHandleNextStep`로 변경하는 건 어떻게 생각하시나요?

혹시, 제가 wiki를 잘못 이해했다면 흘려주세요 ㅎㅎ..

2024-02-23 13:26 UTC, coggiee reviewed
늦어져서 죄송합니다.. 정말 고생 많으셨습니다! 👍

다른 분들이 의견을 많이 남겨주셔서 크게 남길 것은 없었어요. 대신, react-query를 굉장히 잘 사용하시는 것 같아 많이 배우고 갑니다. 😃

2024-02-23 13:26 UTC, coggiee commented on app/signup/_hooks/useMutationDeleteUser.ts
> +  });
tanstack-query 숙숙 잘 만드시는게 부럽네요... 👍

2024-02-24 09:40 UTC, bgyoons reviewed
고생 많으셨습니다 👍 
리뷰 확인해주시고 반영되면 다시 재리뷰 하겠습니다 ~!
다음 번에는 PR 단위를 작게 쪼개서 작업해보아요! :D

2024-02-24 09:40 UTC, bgyoons commented on app/_common/store/useUserStore.ts
유저 정보는 세션 스토리지에 저장 안하고 로컬 스토리지에 저장하시는 걸까요?

2024-02-24 09:40 UTC, bgyoons commented on app/_common/utils/cookie.ts
> +"use server";
아직 nextjs 공부 중이라 이것도 처음 알았네요 👍

2024-02-24 09:40 UTC, bgyoons commented on app/login/_components/LoginForm.tsx
> +"use client";
여기에 use client가 사용되는 이유는 뭔가요? :)

2024-02-24 09:40 UTC, bgyoons commented on app/login/_components/StartWithGithubButton.tsx
> +        href={"http://3.38.76.76:8080/oauth2/authorization/github"}
서버 주소는 env에서 불러오는 방식으로 바꾸어도 좋을 것 같습니다 :D

2024-02-24 09:40 UTC, bgyoons commented on app/signup/_components/SignupCompleteModal.tsx
> +  const onCompleted = () => {
이벤트가 연결됐을 때 실제 호출되는 함수는 `on-` prefix가 아닌 `handle-` prefix로 컨벤션을 정했어서 수정해주시면 감사하겠습니다!

2024-02-24 09:40 UTC, bgyoons commented on app/signup/_components/SignupFirstStep.tsx
> +    // setValue("username", "mibu119");
TODO 관련 주석도 없는 것 같아서, 이런 주석은 최대한 삭제하는게 좋을 것 같아요!

2024-02-24 09:40 UTC, bgyoons commented on app/signup/_components/SignupForm.tsx
> +  const { data: userData } = useQuerySignUpUser();
로컬에서 돌려봤는데 /signup 으로 가면 바로 401에러가 떠서, axios 인스턴스 쓰는 부분에서 종운님이 말씀하셨던 것처럼 try/catch 등으로 에러 처리도 해주셔야할 것 같아요!

<img width="1677" alt="스크린샷 2024-02-24 오후 6 37 26" src="https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/73841260/9ff18d1e-6457-4466-bfb6-f1da4c336d0b">

2024-02-24 09:51 UTC, bgyoons commented on app/_common/store/useStore.ts
이 파일은 어디에 사용되는 건가요?

2024-02-26 00:13 UTC, bel1c10ud approved these changes

2024-02-26 00:17 UTC, bgyoons approved these changes

2024-02-26 00:22 UTC, merged