[style] accordion variant 옵션 추가
Open-Eye-Im-Developer/MoGakGo-FE pull request #183
Opened 2024-03-14 09:53 UTC by coggiee

# 📌 작업 내용
- [x] accordion 컴포넌트에 variant 옵션 추가
  1. outline
  2. default

![스크린샷 2024-03-14 18 49 11](https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/101445377/29f1f27f-3eec-4c49-a3ce-04ba6d9b42ec)

# 🚦 특이 사항
- 주의깊게 봐야하는 PR 포인트 & 말하고 싶은 점을 작성해주세요.

2024-03-14 10:12 UTC, mibu119 requested changes
확인 부탁드립니다!

2024-03-14 10:12 UTC, mibu119 commented on app/_common/shadcn/ui/accordion.tsx
> +    className={cn(className, accordionVariants({ variant }))}
저도 이거 항상 헷갈리는데요.
컴포넌트 커스텀 자율성을 위해서 넣은 className이 순서가 앞으로 오면 의도한대로 적용이 안될 수 있어요. 
순서가 저도 헷갈려서...이렇게 수정 제안드려요.
```suggestion
    className={cn(accordionVariants({ variant, className }))}
```

+) 확인해보니까 badge.ts의 className은 순서가 뒤에 가있더라구요 이것도 혹시 모르니 마찬가지로 Variants 안으로 옮겨주세요~

2024-03-14 10:13 UTC, mibu119 commented on app/_common/shadcn/ui/accordion.tsx
> +    className={cn(className, accordionVariants({ variant }))}
tailwind css class 적용 순위에 관해서 제가 [카카오 블로그](https://fe-developers.kakaoent.com/2022/220303-tailwind-tips/)  읽어본건데
참고하시라구 두고 갈게요!
![스크린샷 2024-03-14 오후 7 04 31](https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/114740795/04da74a6-1017-41e7-8ab6-0457ee829b99)

2024-03-14 11:23 UTC, coggiee commented on app/_common/shadcn/ui/accordion.tsx
> +    className={cn(className, accordionVariants({ variant }))}
수정했습니다!

2024-03-15 01:15 UTC, bgyoons approved these changes
고생 많으셨습니다!! 👍

2024-03-15 01:47 UTC, mibu119 approved these changes

2024-03-15 01:47 UTC, merged